steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', 'gcr.io/pow-spinnaker/sample-app:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/pow-spinnaker/sample-app']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/sample-app', 'my-container=gcr.io/pow-spinnaker/sample-app']
  env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-centeral1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=pow-spinnaker'
  # images: ['gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', 'gcr.io/pow-spinnaker/sample-app:latest']
