steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', 'gcr.io/pow-spinnaker/sample-app:latest']
- name: 'gcr.io/pow-spinnaker/gcloud'
  args: ['auth', 'configure-docker']
- name: 'gcr.io/pow-spinnaker/docker'
  args: ['push', 'gcr.io/pow-spinnaker/sample-app']
- name: 'gcr.io/pow-spinnaker/kubectl'
  args: ['set', 'image', 'deployment/sample-app', 'my-container=gcr.io/pow-spinnaker/sample-app']
  # images: ['gcr.io/pow-spinnaker/sample-app:$SHORT_SHA', 'gcr.io/pow-spinnaker/sample-app:latest']
